#!/bin/bash -e

FAILURE_COUNT=0
STARTING=1

while true; do
  if /usr/bin/pg_isready --quiet --host=localhost --timeout=10 ; then
    FAILURE_COUNT=0
    STARTING=0
  else
    FAILURE_COUNT=$((FAILURE_COUNT + 1))
  fi

  # At least once in the history the test has to succeed.
  if [ "$STARTING" -eq "0" ]; then
    # If twice in a row the test failed, it kills the container.
    if [ "$FAILURE_COUNT" -eq "2" ]; then
      echo "Killing the container."
      kill 1
    fi
  fi

  # Check every 30 seconds.
  sleep 30
done
