#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/postgresql
  chown nobody:nogroup /var/log/postgresql

  exec chpst -u nobody:nogroup svlogd -tt /var/log/postgresql
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?:(?P<time___time__LogPostgreSQL__RFC3339Milli__UTC__UTC___optional>\\d+-\\d+-\\d+ \\d+:\\d+:\\d+\\.\\d+ \\S+) \\[(?P<pid___int___optional>\\d+)\\] (?:(?P<user___optional>\\S+)@(?P<database___optional>\\S+) )?(?P<level___optional>\\S+):\\s+)?(?P<msg>.+?)\\s*$"
fi
