#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/postgresql
  chown nobody:nogroup /var/log/postgresql

  exec chpst -u nobody:nogroup svlogd -tt /var/log/postgresql
else
  # TODO: Exit with 115. See: https://gitlab.com/tozd/dinit/-/issues/1
  exec chpst -u nobody:nogroup cat
fi
