#!/bin/bash -e

POSTGRES=/usr/lib/postgresql/9.3/bin/postgres
DATADIR=/var/lib/postgresql/9.3/main
CONFDIR=/etc/postgresql/9.3/main

mkdir -p "${DATADIR}"
chmod 700 "${DATADIR}"
chown postgres:postgres "${DATADIR}"

# If data directory is empty, we restore it from our copy of initial PostgreSQL database files.
if ! [[ $(ls -A "${DATADIR}" | grep -v placeholder) ]]; then
  cp -a /var/lib/postgresql.orig/9.3/main/* "${DATADIR}/"
fi

# Is there any other script to run here?
[ -f /etc/service/postgresql/run.initialization ] && source /etc/service/postgresql/run.initialization

exec chpst -u postgres:postgres:ssl-cert "${POSTGRES}" -D "${DATADIR}" -c config_file="${CONFDIR}/postgresql.conf" 2>&1
