#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

VERSION=$(ls -1 /var/lib/postgresql.orig/)

if [[ $(echo "$VERSION" | wc -l) -ge 2 ]]; then
  echo "Multiple versions?"
  exit 1
fi

POSTGRES="/usr/lib/postgresql/$VERSION/bin/postgres"
DATADIR="/var/lib/postgresql/$VERSION/main"
CONFDIR="/etc/postgresql/$VERSION/main"

pgsql_command()
{
  local cmd="$1"
  # We hide the prompt by redirecting stdout to /dev/null and then redirect stderr to (new) stdout.
  # One reason we are hiding the prompt is because it does not end with a newline so it merges with the next log line.
  chpst -u postgres:postgres:ssl-cert "${POSTGRES}" --single -D "${DATADIR}" -c config_file="${CONFDIR}/postgresql.conf" <<< "${cmd}" 2>&1 >/dev/null
}

mkdir -p "${DATADIR}"
chmod 700 "${DATADIR}"
chown postgres:postgres "${DATADIR}"

# If data directory is empty, we restore it from our copy of initial PostgreSQL database files.
if ! [[ $(ls -A "${DATADIR}" | grep -v placeholder) ]]; then
  cp -a /var/lib/postgresql.orig/$VERSION/main/* "${DATADIR}/"

  # TODO: Support automatic creation of more than one role and database.
  if [[ -n "${PGSQL_ROLE_1_USERNAME}" && -n "${PGSQL_ROLE_1_PASSWORD}" ]]; then
    pgsql_command "CREATE ROLE ${PGSQL_ROLE_1_USERNAME} WITH ${PGSQL_ROLE_1_FLAGS} ENCRYPTED PASSWORD '${PGSQL_ROLE_1_PASSWORD}';"
  fi
  if [[ -n "${PGSQL_DB_1_NAME}" && -n "${PGSQL_DB_1_OWNER}" ]]; then
    pgsql_command "CREATE DATABASE ${PGSQL_DB_1_NAME} WITH OWNER ${PGSQL_DB_1_OWNER} ENCODING '${PGSQL_DB_1_ENCODING:-UNICODE}' LC_COLLATE '${PGSQL_DB_1_LC_COLLATE}' LC_CTYPE '${PGSQL_DB_1_LC_CTYPE}' TEMPLATE ${PGSQL_DB_1_TEMPLATE:-DEFAULT};"

    if [[ -n "${PGSQL_DB_1_POSTGIS}" ]]; then
      # Cannot create PostGIS extension in single-user mode, so we need to
      # start the server up for a bit; listen on localhost so external users
      # don't connect during this short initialization phase.
      chpst -u postgres:postgres:ssl-cert "${POSTGRES}" -D "${DATADIR}" -c config_file="${CONFDIR}/postgresql.conf" -c listen_addresses=127.0.0.1 2>&1 &
      TMP_PID="$!"
      while ! pg_isready >/dev/null ; do
        sleep 1
      done
      /usr/bin/psql -U postgres -c "CREATE EXTENSION postgis;" -d "${PGSQL_DB_1_NAME}" 2>&1 || true
      kill "$TMP_PID"
      wait "$TMP_PID"
    fi
  fi
fi

# Is there any other script to run here?
[ -f /etc/service/postgresql/run.initialization ] && source /etc/service/postgresql/run.initialization

# Redirect PostgreSQL's log to stdout.
mkdir -p "${DATADIR}/log"
chown postgres:postgres "${DATADIR}/log"
ln -sf /dev/stdout "${DATADIR}/log/postgresql.json"
chown -h postgres:postgres "${DATADIR}/log/postgresql.json"

# We redirect stdout to stderr for initial (non-JSON) log messages.
# Regular logging goes to stdout later on by the log service.
exec chpst -u postgres:postgres:ssl-cert "${POSTGRES}" -D "${DATADIR}" -c config_file="${CONFDIR}/postgresql.conf" 1>&2
